#!/bin/bash

now=$(data + "%m_%d_%Y)

function shuffle {
    java -Xms1G -Xmx8G -jar ./build/libs/LabelAlgorithm-0.2 --shuffle --heurshuffle --vertices 1000 --density 0.5 --output "results/Shuffle1000Vertices_$now.txt"
}

"$@"
